apiVersion: v2
name: red-chart
description: A Helm chart for deploying web applications with Istio service mesh, cert-manager, and Traefik integration
type: application
version: 0.1.2
appVersion: "1.0.0"
home: https://github.com/RussellGilmore/red-charts
sources:
  - https://github.com/RussellGilmore/red-charts
maintainers:
  - name: Russell Gilmore
    email: Russell.Gilmore@pm.me
keywords:
  - istio
  - traefik
  - cert-manager
  - nginx
  - web-app
annotations:
  category: Web Applications
kubeVersion: ">=1.24.0-0"
