---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "red-chart.fullname" . }}-config
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "red-chart.labels" . | nindent 4 }}
data:
  index.html: |
    {{- tpl .Values.content.html . | nindent 4 }}
